### PR TITLE
Fixed the back button issue

### PR DESCRIPTION
**Pull request by AbhishekBhamare**

### CODE REVIEW

**Comment by yashsehgal** [comment]
Thanks for working on this issue @AbhishekBhamare ⭐ 
Can you follow these steps, after this, your PR will be merged.

- We have some large amount of changes in our `development` branch getting merged to master/production. Thus you need to take a pull from `master` branch and then push the changes. 

The above step might be a lengthy task as the code might get into some merge conflicts. But feel free to collaborate here in the comment section (discussions).

Thanks again for fixing that issue! 💯

**Comment by AbhishekBhamare** [comment]
Hi @yashsehgal Can you tell me what I need to do differently to get my PR merged. I'm still a rookie.

**Comment by yashsehgal** [comment]
That's fine @AbhishekBhamare I am merging the `development` branch to the `master` branch, you just have to take a pull from the `master` branch. This might help you
```cmd
git pull
```
Or this
```cmd
git pull origin master
```

After this, there are chances that you'll get some conflicts. If you get any, we can discuss how to resolve them here. Don't worry about that part. 👍🏽

**Comment by AbhishekBhamare** [comment]
@yashsehgal I have executed git pull command on my local repository without any conflict.

**Comment by yashsehgal** [comment]
That's great, Just check if anything is breaking or not after running the react app. If everything is working, we are good to merge.

**Comment by AbhishekBhamare** [comment]
React app is working fine.

**Comment by yashsehgal** [comment]
That's great @AbhishekBhamare You can push your changes to this PR. I will review that 👍🏽

**Comment by AbhishekBhamare** [comment]
@yashsehgal  I've already pushed the changes

**Pull request closed without merging**
